/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloConection.ConexaoBD;
import modeloDao.DaoServidor;
import modeloBeans.BeansServidor;
import modeloBeans.ModeloTabela;
        

/**
 *
 * @author Note
 */
public final class FormServidor extends javax.swing.JFrame {
    
    BeansServidor mod = new BeansServidor();
    DaoServidor control = new DaoServidor();
    ConexaoBD conex = new ConexaoBD();
    int flag =0;

    /**
     * Creates new form FormMedico
     */
    public FormServidor() {
        initComponents();
        preencherTabela("select *from servidores order by ser_nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxSerFuncao = new javax.swing.JComboBox<>();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServidores = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jFormattedTextFieldCel = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jtCOD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setText("Nome");

        jLabel3.setText("Celular");

        jLabel4.setText("Função");

        jTextFieldNome.setEnabled(false);

        jComboBoxSerFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agente Penitenciário", "Agente Socioeducativo", "Técnico Administrativo", "Motorista", "Médico", "Enfermeiro", "Técnico em Enfermagem", "Piscólogo", "Assistente Social", "Chefe de Oficina", "Chefe de Serviço", "Digitador", "Estagiário", "Vigilante", "Funcionário de Empresa Conveniada", " " }));
        jComboBoxSerFuncao.setEnabled(false);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableServidores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableServidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableServidoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableServidores);

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jFormattedTextFieldCel.setEnabled(false);
        jFormattedTextFieldCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCelActionPerformed(evt);
            }
        });

        jLabel5.setText("ID: ");

        jtCOD.setEnabled(false);

        jLabel6.setText("CPF");

        jLabel7.setText("Matricula");

        jLabel8.setText("E-mail");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 594, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonCancelar)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jtCOD, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxSerFuncao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovo)
                    .addComponent(jtCOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSerFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButtonEditar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CADASTRO DE SERVIDORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        setSize(new java.awt.Dimension(951, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Nome para continuar");
            jTextFieldNome.requestFocus();
        }else if(jTextFieldCpf.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o CPF para continuar");
            jTextFieldCpf.requestFocus();
        }else
        if(flag==1){
        mod.setSerNome(jTextFieldNome.getText()); 
        mod.setSerCpf(jTextFieldCpf.getText());
        mod.setSerMatricula(jTextFieldMatricula.getText());
        mod.setSerCelular(jFormattedTextFieldCel.getText());
        mod.setSerEmail(jTextFieldEmail.getText());
        mod.setSerFuncao((String) jComboBoxSerFuncao.getSelectedItem());
        control.Salvar(mod);
        jTextFieldNome.setText("");
        jTextFieldCpf.setText("");
        jTextFieldMatricula.setText("");
        jFormattedTextFieldCel.setText("");
        jTextFieldEmail.setText("");
        jTextFieldNome.setEnabled(false);
        jTextFieldCpf.setEnabled(false);
        jTextFieldMatricula.setEnabled(false);
        jFormattedTextFieldCel.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jComboBoxSerFuncao.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        preencherTabela("select *from servidores order by ser_nome");
        }else{
        mod.setSerCod((Integer.parseInt(jtCOD.getText())));
        mod.setSerNome(jTextFieldNome.getText());
        mod.setSerCpf(jTextFieldNome.getText());
        mod.setSerFuncao((String)jComboBoxSerFuncao.getSelectedItem());
        mod.setSerCelular(jFormattedTextFieldCel.getText());
        control.Editar(mod);
        jtCOD.setText("");
        jTextFieldNome.setText("");
        jTextFieldCpf.setText("");
        jTextFieldMatricula.setText("");
        jFormattedTextFieldCel.setText("");
        jTextFieldEmail.setText("");
        jTextFieldNome.setEnabled(false);
        jTextFieldCpf.setEnabled(false);
        jTextFieldMatricula.setEnabled(false);
        jFormattedTextFieldCel.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jComboBoxSerFuncao.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        preencherTabela("select *from servidores order by ser_nome");
        
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag=1;
        jTextFieldNome.setEnabled(true);
        jTextFieldCpf.setEnabled(true);
        jTextFieldMatricula.setEnabled(true);
        jFormattedTextFieldCel.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jComboBoxSerFuncao.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldNome.setText("");
        jTextFieldCpf.setText("");
        jTextFieldMatricula.setText("");
        jFormattedTextFieldCel.setText("");
        jTextFieldEmail.setText("");
        jTextFieldPesquisa.setText("");
        jtCOD.setText("");
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setSerPesquisa(jTextFieldPesquisa.getText());
        BeansServidor model = control.buscaServidor(mod);
        jTextFieldNome.setText(model.getSerNome());
        jtCOD.setText(String.valueOf(model.getSerCod()));
        jFormattedTextFieldCel.setText(String.valueOf(model.getSerCelular()));
        jComboBoxSerFuncao.setSelectedItem(model.getSerFuncao());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNome.setEnabled(!true);
        jFormattedTextFieldCel.setEnabled(!true);
        jComboBoxSerFuncao.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
        jtCOD.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldCel.setText("");
        preencherTabela("select *from servidores order by ser_nome");
         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag=2;
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCel.setEnabled(true);
        jComboBoxSerFuncao.setEnabled(true);
        jTextFieldCpf.setEnabled(true);
        jTextFieldMatricula.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabela("select *from servidores order by ser_nome");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta =0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir?");
        if (resposta ==JOptionPane.YES_OPTION){
            mod.setSerCod(Integer.parseInt(jtCOD.getText()));
            control.Excluir(mod);
        jtCOD.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldCel.setText("");
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCel.setEnabled(false);
        jComboBoxSerFuncao.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabela("select *from servidores order by ser_nome");
        }
                    
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableServidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableServidoresMouseClicked
        String ser_nome;
        ser_nome = ""+jTableServidores.getValueAt(jTableServidores.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select *from servidores where ser_nome='"+ser_nome+"'");
        try{
            conex.rs.first();
            jtCOD.setText(String.valueOf(conex.rs.getInt("ser_cod")));
            jTextFieldNome.setText(conex.rs.getString("ser_nome"));
            jTextFieldCpf.setText(conex.rs.getString("ser_cpf"));
            jTextFieldMatricula.setText(conex.rs.getString("ser_matricula"));
            jTextFieldEmail.setText(conex.rs.getString("ser_email"));
            jComboBoxSerFuncao.setSelectedItem(conex.rs.getString("ser_funcao"));
            jFormattedTextFieldCel.setText(conex.rs.getString("ser_celular"));
        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar dados."+ex);
        }
        conex.desconecta();
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableServidoresMouseClicked

    private void jFormattedTextFieldCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCelActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();        
        String [] colunas = new String [] {"ID","Nome","CPF","Matricula","Celular","E-mail","Função"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first(); 
            do{
                dados.add(new Object[]{conex.rs.getInt("ser_cod"),conex.rs.getString("ser_nome"),conex.rs.getString("ser_cpf"),conex.rs.getString("ser_matricula"),conex.rs.getString("ser_celular"),conex.rs.getString("ser_email"),conex.rs.getString("ser_funcao")});
            }while(conex.rs.next());
        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao preencher ArrayList"+ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTableServidores.setModel(modelo);
        jTableServidores.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableServidores.getColumnModel().getColumn(0).setResizable(false);
        jTableServidores.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableServidores.getColumnModel().getColumn(1).setResizable(false);
        jTableServidores.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableServidores.getColumnModel().getColumn(2).setResizable(false);
        jTableServidores.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTableServidores.getColumnModel().getColumn(3).setResizable(false);
        jTableServidores.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTableServidores.getColumnModel().getColumn(4).setResizable(false);
        jTableServidores.getColumnModel().getColumn(5).setPreferredWidth(180);
        jTableServidores.getColumnModel().getColumn(5).setResizable(false);
        jTableServidores.getColumnModel().getColumn(6).setPreferredWidth(180);
        jTableServidores.getColumnModel().getColumn(6).setResizable(false);
        jTableServidores.getTableHeader().setReorderingAllowed(false);
        jTableServidores.setAutoResizeMode(jTableServidores.AUTO_RESIZE_OFF);
        jTableServidores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);        
        conex.desconecta();
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxSerFuncao;
    private javax.swing.JFormattedTextField jFormattedTextFieldCel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServidores;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jtCOD;
    // End of variables declaration//GEN-END:variables

    private static class SQLException {

        public SQLException() {
        }
    }

    private static class jTableServidores {

        public jTableServidores() {
        }
    }

}
